### ISSUE TITLE
ubuntu 20.04 creation using packer got stuck

### ISSUE THREAD

**Issue by ping2balaji** [mrtrkmnhub/ubuntu-packer#1]
Hi @mrtrkmn ,

Thanks for this repo with detailed info about creating ubuntu VM with packer.

I have tried the steps you have mentioned but got stuck in "waiting for ssh". Tried rdp and following is the output:

![image](https://user-images.githubusercontent.com/23480027/144980090-5a193655-fb01-46ea-980d-91df18f3d41d.png)

Please let me know any way to resolve this.

Thanks,
...Balaji.J

**Comment by mrtrkmn** [comment]
are you trying to create the vm in a vm ? @ping2balaji

**Comment by bjeyabalan** [comment]
Hi @mrtrkmn ,

The issue got resolved after i moved my host os from ubuntu server to ubuntu desktop.
Not sure what fixed it though.

However im  facing following issue with virtualbox now while packer is provisioning the VM: 
"VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine"

The VM abruptly stops with above error from VirtualBox and this is happening at random times like after 5mins sometme and after 30mins sometimes. Any input here?
I checked internet and updated virtualbox to latest version.
My host is Ubuntu 20.04.

Please let me know ur suggestion.

Thanks,
...Balaji

**Comment by ping2balaji** [comment]
Hi @mrtrkmn , the above issue is fixed after updating the vbox extension to same version as vbox. 
thanks,
...Balaji
